### ISSUE TITLE
Biigle on Jetson TX2

### ISSUE THREAD

**Issue by mzur** [biigle/core#139]
I created an [`arm32v6`](https://github.com/BiodataMiningGroup/biigle-core/tree/arm32v6) branch with the configuration that worked on the Raspberry Pi 3. We can use it to build Biigle on the Jetson TX2. However installing Docker there seems not to be straight forward. More information on that is [here](https://devtalk.nvidia.com/default/topic/1000224/jetson-tx2/docker-on-the-tx2/1).

Edit: A probably even better starting point is [this](https://github.com/Technica-Corporation/Tegra-Docker).

Edit 2: It seems like [JetPack 3.2](https://developer.nvidia.com/embedded/jetpack) has out of the box Docker support.

**Comment by marinmarcillat** [comment]
Hello ! Thanks for your amazing job on Biigle ! And sorry to bring back this old issue.
I have been trying to build a local biigle instance on a rpi4 (with raspi os 64 bit), but I have been facing issues with the arm architecture packages.
First, there were issues when running `FROM docker.pkg.github.com/biigle/core/app:arm64v8` in the build.dockerfile, so I changed it to `FROM ghcr.io/biigle/core/app:arm64v8` which gave me a `manifest unknown` error.
Any idea on how to solve this ?

**Comment by mzur** [comment]
Sorry but the `arm*` branches were terribly out of date. I've updated them now, so please update your local repo. As to your error: If you want to build `biigle/biigle` in an `arm*` branch, you also need to build `biigle/core` in an `arm*` branch locally, as we don't provide official base images for that architecture. So you have to clone `biigle/core` to your Pi and run `./build.sh` (say "no" when it asks you to publish on GitHub). Now you have the required base images locally on your Pi and you can proceed to build `biigle/biigle`.

Please open a [new discussion](https://github.com/orgs/biigle/discussions) if you have any follow-up questions on that. This makes the information more findable if anyone has a similar question in the future.
