### ISSUE TITLE
Error pages

### ISSUE THREAD

**Issue by mzur** [biigle/core#2]
Create views for the HTTP Exceptions that can occur in `resources/views/errors`.

**Comment by dlangenk** [comment]
Updated more "mature" version. Also fancy https://dribbble.com/shots/4495893-There-is-no-light and https://dribbble.com/shots/10490039-404-Not-Found

<img width="638" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/4822085/206522674-c74e4103-94b4-4311-b057-b9967a2f7282.png">
<img width="763" alt="PastedGraphic-2" src="https://user-images.githubusercontent.com/4822085/206522678-8e705432-2df7-4fa8-9e2a-a59de23c467d.png">
