### ISSUE TITLE
Federated global search for projects, volumes and label trees

### ISSUE THREAD

**Issue by mzur** [biigle/core#208]
The centralized user and label tree repository (#169) has no longer a real use case. Label trees can now be easily transferred between BIIGLE instances (biigle/label-trees#33). Instead, the idea came up to create a global search for all BIIGLE instances. This would be a single service where users can search for projects, volumes, videos and label trees in many (all) different BIIGLE instances. To implement this, the new concept of public projects would have to be introduced. These projects would be accessible by anyone, even users without an account in the BIIGLE instance where the project is stored. The global search service would regularly crawl the connected BIIGLE instances to index the available public projects, volumes, videos and label trees.

**Comment by mzur** [comment]
This can even be implemented in BIIGLE (as a new module) instead of an extra service. Search results for projects, volumes, videos and label trees are displayed on the regular search page and marked as "external" with a link to the respective model in the external BIIGLE instance. The BIIGLE instance regularly crawls the other instances to which it is connected. Connected instances can be configured in the admin area.

**Comment by mzur** [comment]
I had a new idea which would work without the concept of public projects and label trees:

Other BIIGLE instances can be connected via the admin panel. Each instance gets a database entry and an API token similar to the API tokens of the users (displayed only once, can be revoked/renewed). All connected other instances can access the search index API endpoint of the current instance using their API token. The API endpoint returns a list of _all_ projects, label trees and volumes of the current instance. This includes their URL, name, description and updated_at column. In addition to that, the information on which user is allowed to access which project, label tree or volume is included as well. Users are anonymously identified by their UUID. The index data can consist of a single large JSON. The JSON could be prepared on scheduled intervals (every hour?) and stored in the cache so index requests get a quick response.

Each connected BIIGLE instance can in turn be crawled by the current instance (controlled by a switch attribute). Admins can also specify the interval at which index requests are sent (mimimum: one hour, see above). Three new database tables are added to accomodate the indexed data. One table for the project, label tree and volume information, one table for the user UUIDs and one pivot table specifying which user UUID is allowed to see which project, label tree or volume. Each project, label tree, volume and UUID is associated with the ID of the connected BIIGLE instance so they can be synchronized with every index request (else you wouldn't know which rows can be deleted).

The search page then includes the indexed models in the search results (plainly marking them as "external"). The links point to the URL of the external BIIGLE instance. Optionally a user can hide search results for external models with a checkbox in the search view. The checkbox value should be persistently stored in the user options.

**Comment by mzur** [comment]
Side note: Videos will be associated with volumes so they don't need to be indexed separately ( #276 ).

**Comment by mzur** [comment]
This should be integrated in biigle/core, else the search results for external models can't be seamlessly integrated.

**Comment by tschoeni** [comment]
That would be absolutely awesome!
