### ISSUE TITLE
Upgrade OpenLayers

### ISSUE THREAD

**Issue by mzur** [biigle/core#250]
Upgrade OpenLayers to version 6 as it offers better support for touch and pen input devices (openlayers/openlayers#9244). This is a major version bump and might be complicated to integrate with our existing modifications to OpenLayers.

**Comment by mzur** [comment]
I pushed an experimental implementation of an OpenLayers 9 WebGL vector layer to [`ol-v9-webgl`](https://github.com/biigle/core/tree/ol-v9-webgl). This has *dramatic* performance improvements for rendering images with lots of annotations. The WebGL vector layer is still experimental even in OpenLayers, though. Issues at first glance:

- Only polygons are drawn. Points should be supported but were not drawn (maybe because of a missing style definition).
- Circles, rectangles, ellipses are not supported.
- Feature hit detection worked only on the outlines, not the interior of the polygons.

Implementing rectangles and ellipses in WebGL would be tremendous effort but the speed improvements might be worth it once all this is no longer experimental in OpenLayers.

**Comment by dlangenk** [comment]
Can we upgrade to v9 without webgl vector layer more easily? This would at least improve tablet support (and would likely make the webgl transform easier once it is stable).

**Comment by mzur** [comment]
Yes, this is the intention behind #868.
