### ISSUE TITLE
Filter wording incorrect

### ISSUE THREAD

**Issue by dlangenk** [biigle/core#292]
When selecting has annotation from user it asks for the "User name", however it expects the first/second name.

**Comment by mzur** [comment]
We have no user name other than the firstname and lastname of the users in BIIGLE. The only other identifier is the email address which should be private. I thought "User name" would be more concise than "User firstname and/or lastname". What do you propose to use instead?

**Comment by dlangenk** [comment]
For me that was clear as well. But a user had problems with this because he tried the login email. Probably just name. But we could also just leave it as it is.

**Comment by mzur** [comment]
I say we should leave it like it is. If this issue occurs more often, we can reconsider.
