### ISSUE TITLE
If volume creation fails, Biigle manipulates input fields

### ISSUE THREAD

**Issue by dlangenk** [biigle/core#293]
If you want to create a volume but an error occurs, the volume url changes to [object Object] instead of the string which was in there before. The same happened to the Volume files and the media type which is simply unset. Although it does not happen all the time 🤷‍♂️

<img width="549" alt="proof" src="https://user-images.githubusercontent.com/4822085/95440822-aaf73880-0959-11eb-9aca-6eeef7849eec.png">

**Comment by mzur** [comment]
Can you please tell me the exact values that you used? And how did you manage to unselect the media type buttons?

**Comment by dlangenk** [comment]
It's basically this volume https://biigle.de/volumes/edit/2878 with the exact same settings except that the filename had ticks around them when a space was used, as output by ls -m (see below). When I clicked on create I got the error message. I changed the filenames by removing the single ticks and clicked on submit again. It didn't work again. So I deleted all the filenames and tried with the one from the image above and clicked again. Then I noticed that the Volume type unselected itself and the volume url was object Object.

`'2013-08-19 17.55.28.jpg', '2013-08-22 15.19.06.jpg', '2013-08-22 15.19.12.jpg', '2013-08-22 15.19.39.jpg', '2013-08-25 17.46.36.jpg',
'2013-09-09 12.21.59.jpg', '2013-09-09 12.22.22.jpg', '2013-09-09 12.22.29.jpg', '2013-09-21 13.53.15.jpg', '2014-08-08 09.27.01.jpg',
Abblättern-02.jpg, Abblättern.JPG, 'Abblättern und Kanten.JPG', 'Abblätterung 1.JPG', 'Abblätterung 2.JPG', 'Abblätterung (2).JPG',
'Abblätterung (3).JPG', 'Abblätterung (4).JPG', 'Abblätterung (5).JPG', 'Abblätterung (6).JPG', 'Abblätterung (7).JPG', Abblätterung.JPG,
DSC03043.JPG, DSC03317.JPG, DSCF0937.JPG, DSCN0533.JPG, DSCN0534.JPG, DSCN0617.JPG, DSCN0639.JPG, DSCN0642.JPG, DSCN0643.jpg, DSCN0659.JPG,
DSCN0674.JPG, DSCN0683.JPG, DSCN0686.JPG, DSCN0984.JPG, DSCN1058.JPG, DSCN1089.JPG, DSCN1294.JPG, DSCN1298.JPG, DSCN1352.JPG, DSCN1376.JPG,
DSCN1394.JPG, DSCN1406.JPG, DSCN1771.JPG, DSCN1783.JPG, DSCN1792.JPG, DSCN1801.JPG, DSCN1802.JPG, DSCN1861.JPG, DSCN1894.JPG, DSCN1973.JPG,
DSCN1983.JPG, DSCN1998.JPG, DSCN2006.JPG, DSCN2016.JPG, DSCN2043.JPG, DSCN2051.JPG, DSCN2052.JPG, DSCN2087.JPG, DSCN2196.JPG, DSCN2198.JPG,
DSCN2208.JPG, DSCN2211.JPG, DSCN2236.JPG, DSCN2248.JPG, DSCN2298.JPG, DSCN2352.JPG, DSCN2393.JPG, DSCN2432.JPG, DSCN2507.JPG, DSCN2511.JPG,
DSCN2513.JPG, DSCN2516.JPG, DSCN2522.JPG, DSCN2525.JPG, DSCN2527.JPG, DSCN2528.JPG, DSCN2530.JPG, DSCN2534.JPG, DSCN2541.JPG, DSCN2545.JPG,
DSCN2546.JPG, DSCN2547.JPG, DSCN2548.JPG, DSCN2555.JPG, DSCN2561.JPG, DSCN2565.JPG, DSCN2567.JPG, DSCN2570.JPG, DSCN2574.JPG, DSCN2592.JPG,
DSCN2599.JPG, DSCN2623.JPG, DSCN2639.JPG, IMAG1206.jpg, image107.JPG, image134.JPG, image430.JPG, image92.JPG, image93.JPG,
IMG00129-20100618-0116.jpg, IMG_1076.JPG, IMG_1101.JPG, IMG_1161.JPG, IMG_1168.JPG, IMG_1171.JPG, IMG_1208.JPG, IMG_1287.JPG, IMG_1312.JPG,
IMG_1335.JPG, IMG_1364.JPG, IMG_1376.JPG, IMG_1442.JPG, IMG_1469.JPG, IMG_1474.JPG, IMG_1478.JPG, IMG_1490.JPG, IMG_1497.JPG, IMG_1521.JPG,
IMG_1522.JPG, IMG_1590.JPG, IMG_1624.JPG, IMG_1626.JPG, IMG_1639.JPG, IMG_1665.JPG, IMG_1690.JPG, IMG_1691.JPG, IMG_1693.JPG, IMG_1734.JPG,
IMG_1755.JPG, IMG_1782.JPG, IMG_1799.JPG, IMG_20191002_123325.jpg, IMG_2946.JPG, IMG_2956.JPG, IMG_2958.JPG, IMG_2963.JPG, IMG_2967.JPG,
IMG_2994.JPG, IMG_3071.JPG, IMG_3105.JPG, IMG_3106.JPG, IMG_3130.JPG, 'Keine Haftung Top Coat.jpg', PICT2389.JPG, PICT2492.JPG, PICT2502.JPG,
'Resize of DSC_1996.JPG', Topcoat.jpg`

**Comment by mzur** [comment]
Thanks, it was an issue with the enclosing `'`.
