### ISSUE TITLE
Zoom level decrease after annotation

### ISSUE THREAD

**Issue by dlangenk** [biigle/core#301]
When you use the Volume Label Review tool, then zoom in and create an annotation the zoom level decreases automatically after creating the annotation. (I filtered the list of annotations too).

**Comment by mzur** [comment]
Which annotation shape did you use?

**Comment by dlangenk** [comment]
Polygon with magic lasso and Polygon with paintbrush

**Comment by mzur** [comment]
I couldn't reproduce this. What I did:
1. Select a label
2. Activate Volare
3. Zoom in
4. Draw an annotation (with the brush tool)

The zoom level didn't change (Firefox and Chrome).
