### ISSUE TITLE
hotkey conflict

### ISSUE THREAD

**Issue by dlangenk** [biigle/core#349]
The "change the brush size" hotkey (Shift+mouse wheel) does conflict with the new change the image (Shift+mouse wheel) feature. Probably change the hotkey of change the image to alt? (or strg don't know which one was the zoom functionality in linux)

**Comment by mzur** [comment]
I wanted to change the shortcut to <kbd>Alt</kbd>+Scroll when I noticed that the default behavior of this shortcut is to scroll the browsing history (in Firefox). So this is also a suboptimal choice. Any suggestions?

**Comment by mzur** [comment]
Another idea of mine was to scroll through the images when the mouse hovers over the previous/next image buttons in the tool bar at the bottom. This would work without modifier keys. @dlangenk What do you think?

**Comment by dlangenk** [comment]
Not the best idea. But we could do a toggle with the Shift key. So turn zoom off and on with the shift key. The Windows/Meta/Apple Key is the Zoom in Feature on the Mac, so if Ctrl is the same feature for Linux and Alt is not possible there is no modifier left unfortunately. Otherwise a setting might be possible to use the mouse wheel for zooming or image switch.
