### ISSUE TITLE
Server error on double click to attach video annotation label

### ISSUE THREAD

**Issue by mzur** [biigle/core#410]
It seems to be possible to trigger a server error (i.e. a database unique constraint violation) with a double click when attaching a label to an existing video annotation. Catch these errors and return a correct 400 response. This issue was handled elaborately for image annotations with a [double check](https://github.com/biigle/core/blob/06ffbbda2ca1b4e47cb38b1520d40553286dc94e/app/Http/Controllers/Api/ImageAnnotationLabelController.php#L173-L193). Also implement such a check for video annotations. Ideally, this could share the same logic.

**Comment by lehecht** [comment]
> It seems to be possible to trigger a server error (i.e. a database unique constraint violation) with a double click when attaching a label to an existing video annotation

Somehow I could not reproduce this error. I only get the message 'The user already attached this label to the video annotation.'. My approach was to create some annotations for different labels and then to attach an existing annotation to another label with a double click. What am I doing wrong?
I know where I need to change the code but without testing I cannot make sure that my solution works correctly.
