### ISSUE TITLE
Show complete count of annotations 

### ISSUE THREAD

**Issue by aburfeid** [biigle/core#459]
When annotating (at least for diatoms) you should aim for 400 annotations / slide. A sum of all annotations or all annotations/Slide on the top of the annotations tab would be very helpful.

Thanks in advance.

**Comment by mzur** [comment]
Good idea! The count can be shown in the annotations tab beneath the filter input fields (e.g. "xx annotations"). If a filter is active, the count could show "xx of yy annotations".
