### ISSUE TITLE
Shortcut for “capture screenshot”

### ISSUE THREAD

**Issue by noeliebenoist** [biigle/core#478]
Implement a shortcut for the “capture screenshot” button in the settings sidebar. Suggestion: "P" to take a screenshot of the visible area.

**Comment by mzur** [comment]
A keyboard shortcut can be registered like [this](https://github.com/biigle/core/blob/9d7d543a73b0980b65a745460160d6e8bf7d83c2/resources/assets/js/annotations/components/settingsTab.vue#L164). The screenshot method is available as `capture()` in [this component](https://github.com/biigle/core/blob/master/resources/assets/js/annotations/components/screenshotButton.vue). Finally, this must be mentioned in the [manual](https://github.com/biigle/core/blob/master/resources/views/manual/tutorials/annotations/shortcuts.blade.php).
