### ISSUE TITLE
Catch double-click for point annotations in UI

### ISSUE THREAD

**Issue by mzur** [biigle/core#491]
If people double-click by accident when they create a point annotation, the annotation is duplicated. Catch this and don't allow new annotations within a certain cooldown period (in the UI not the API). This is only relevant for point image annotations (what about whole frame video annotations?).

**Comment by dlangenk** [comment]
I don't see how the whole frame video annotation could be double clicked. There you don't actually click on the image. And double clicking on the button just deactivates it.
