### ISSUE TITLE
Fix rectangle drawing perpendicular to x axis

### ISSUE THREAD

**Issue by mzur** [biigle/core#550]
Rectangles that are perpendicular to the x axis cannot be drawn. This should be fixed. Rectangles perpendicular to the y axis work.

[Screencast from 17.02.2023 14:04:41.webm](https://user-images.githubusercontent.com/2457311/219660683-adee4211-1966-48ff-9416-6333e10a186d.webm)

**Comment by lehecht** [comment]
The bug occurs when a [drawend event](https://github.com/biigle/core/blob/7a4e62b0978338e8de337793778bd8171025fed6/resources/assets/js/annotations/components/annotationCanvas/drawInteractions.vue#L92) is created. You can see this, if you check the coordinates of the feature there. All points are equal which results in a point on the canvas instead of a rectangle.

**Comment by mzur** [comment]
The rectangle shape was added by me on top of the stock OpenLayers (https://github.com/biigle/openlayers). So maybe there is a bug there? Do you have any specific questions about this or need help?

**Comment by mzur** [comment]
So a rectangle is drawn with three clicks, i.e. three coordinates. First, you draw a straight line that determines the first axis of the rectangle. Then you specify the length of the second axis with the third click. The code you linked is executed after the first two clicks were done (`coordinates.length > 2`). The check for `a_vec[1] === 0` must happen because otherwise there can be a division by zero below (line 352).

You are right that it doesn't actually check if the first and second point are equal. Also, I think `[[first, first, first, first]]` is wrong. Maybe `[[first]]` should be returned instead, so the user may try again with the second point.

In addition, while `a_vec[1] === 0` protects against a division by zero below, it doesn't actually do what it should (catch two equal points). It should be `a_vec[0] === 0 && a_vec[1] === 0`. But this doesn't protect against the division by zero any more. In theory, drawing a straight line perpendicular to the x axis should be ok as long as the two points are not equal. Maybe the potential for a division by zero can be removed by unwrapping `tmp` and `a_vec` in line 356, so that `x` is computed only based on values from `first`, `second` and `third`?

**Comment by mzur** [comment]
And to answer the question why the coordinates are recalculated: You don't draw the four points of the rectangle directly. Instead, the points are inferred from the three points you specify (see 1, 2 and 3 in the [diagram](https://github.com/biigle/openlayers/blob/d6b6cfccd5751b7acc93a30688dcf361fff5ce12/src/ol/interaction/Draw.js#L324-L334) which are not equal to the `+` corners of the rectangle).

**Comment by lehecht** [comment]
Can this issue be closed?

**Comment by mzur** [comment]
Yes. Fixed by https://github.com/biigle/openlayers/pull/4
