### ISSUE TITLE
Magic SAM

### ISSUE THREAD

**Issue by mzur** [biigle/core#580]
There was a discussion (https://github.com/orgs/biigle/discussions/566) about a possible implementation of [SAM](https://ai.facebook.com/blog/segment-anything-foundation-model-image-segmentation/) in BIIGLE/MAIA. One application could be a magic wand-like feature in the image annotation tool. @dlangenk implemented a prototype for this (https://github.com/biigle/core/commit/e3d32b39613a69d59c4566f4a72d5d9ed972c355) and it looks really useful.

The feature can be implemented in multiple iterations. First, the basic "point and click" automatic segmentation could be implemented. The embedding of an image is either computed on the fly (if we can dedicate a GPU for this, see discussion) or during a long running "prepare magic SAM" job. If a user activates magic SAM, the embedding is downloaded as well as the model ONNX and the ONNX runtime JS code (we don't want to include the JS code of the runtime in the regular build, so it should be loaded only if the feature is used). Users can then point at a location on the image and get an outline of the automatic segmentation. If they click, the current outline is created as a new polygon annotation (with the currently selected label).

In the next iteration, we could implement UX to select positive and negative examples (what they call prompts with SAM) so users can refine the segmentation outlines of objects. Another idea could be to handle ambiguous segmentations (see the blog post where e.g. either the whole person or only the clothes could be segmented).

Finally, we should consider to replace the existing magic wand feature with magic SAM. We should carefully consider this, though, as I think several users rely on the magic wand and magic SAM will never work exactly the same. Maybe we could implement some feature to collect telemetry how often either feature is used? Or we keep calling both "magic wand" and the users can choose in the annotation tool settings which "algorithm" they want to use (with magic SAM as the default).

**Comment by mzur** [comment]
We really want this. I'll put it on the roadmap and raise the priority.

**Comment by dlangenk** [comment]
Instead of the python script for computing the embedding we could also use torchserve which is likely much more stable. There are already docker instructions for SAM + torchserve [Link](https://github.com/developmentseed/segment-anything-services)

**Comment by mzur** [comment]
I'll have a look but it may still be easier to use the Python script with the current BIIGLE architecture.

**Comment by dlangenk** [comment]
😂 I'd prefer the hat-wizard because of the Magic Sam but all those are great. We could also go for something more descriptive like a point -> polygon symbol but that might be too small for the little button.

**Comment by mzur** [comment]
The hat it is! We don't need a descriptive icon, just an iconic one :wink: 

How did you obtain the ONNX file? I need to take an ONNX of vit_b because I couldn't generate an embedding with vit_h on my machine. If I generate an ONNX with the `export_onnx_model.py` script, inference takes twice as long compared to your file (even if the results make no sense with my vit_b embedding).

**Comment by dlangenk** [comment]
I used the script with colab to generate the onnx. But I can send you my vit_h onnx.

**Comment by mzur** [comment]
I got the vit_h ONNX from your commit, thanks. I'll try to generate a vit_b one with the Colab notebook. Maybe it uses a different onnxruntime :thinking:

**Comment by mzur** [comment]
I had a little fun with the loading animation (but with a serious background):


https://github.com/biigle/core/assets/2457311/98d2a88f-a639-4ad7-b1bd-a9340521ccb5

The regular loading spinner is shown when the embedding is requested, the ONNX is loaded and the model is "warming up". The stars appear if the embedding was not computed yet and it may take a little longer until the tool is ready. I thought it has a nice touch (I'll also add an explaining tooltip). Or is it over the top? :grin:

**Comment by dlangenk** [comment]
I think it's very nice. That's the gamification spirit that makes things fun to use. Luckily it's not Hogwarts themed, so we don't get in trouble with Warners legal department
