### ISSUE TITLE
Improve UI of object tracking rate limiting

### ISSUE THREAD

**Issue by mzur** [biigle/core#609]
If the rate limit for object tracking is reached (#602), an error message is shown. This should be improved UI-wise. The UI can track the number of running object tracking jobs, too, and disable the "track object" button (for points and circles) once the limit is reached. The button can also show the loading spinner that was [recently added](https://github.com/biigle/core/blob/8f9c0864c54bb7ee57d2a910f0ce7ba1bccafbe1/resources/assets/js/annotations/components/controlButton.vue#L58-L61) to the "control button" component. Once a tracking job is finished, the button is enabled again.

**Comment by lehecht** [comment]
Should the tracking of the running jobs just be a frontend thing or can I request the number once from the backend?

**Comment by mzur** [comment]
I leave this up to you. You can get the maximum allowed number of jobs from the [config](https://github.com/biigle/core/blob/c62ac9eb3c5e9bbc8309b9b25cdb721a484cba84/config/videos.php#L53) and then either just track the number of submitted/unfinished tracking requests in the frontend or return the current number of jobs in the response of the "store annotation" request (you can just put it into the annotation object of the response) and use that to track the number of running jobs in the UI. The first approach should work in most cases and the second approach would work even if the user works in two different browser windows in parallel (or opens a different video while the tracking is not finished).
