### ISSUE TITLE
Make dispatching of object tracking events synchonous

### ISSUE THREAD

**Issue by mzur** [biigle/core#615]
The "succeeded" and "failed" events of an object tracking job are sent asynchronously via their own queue jobs:

https://github.com/biigle/core/blob/ac2f57f98b791eed61f8e71bd0f8994b7ddad141/app/Jobs/TrackObject.php#L106-L110

While the TrackObject job itself is processed by a configurable queue (e.g. with a higher priority), the events are pushed to the regular queue. With a busy queue, this could mean that the events are sent (and the user is notified) much later than the job actually finished. Fix this by dispatching the events with `dispatchNow`. It will send the events right from within the TrackObject job.

**Comment by lehecht** [comment]
Maybe I don't get what you want to say but [Events/Dispatchable](https://laravel.com/api/9.x/Illuminate/Foundation/Events/Dispatchable.html) does not contain a method called "dispatchNow".

**Comment by mzur** [comment]
That's right, I just assumed it was there (from the queued job dispatachable). But I think you found the ideal solution with `ShouldBroadcastNow`.
