### ISSUE TITLE
Zooming causes video to disappear in firefox

### ISSUE THREAD

**Issue by lehecht** [biigle/core#626]
After zooming in and out in a video (multiple times), it disappears when firefox is used.

**Comment by lehecht** [comment]
@mzur 
After some research, I found out that this bug has to do with the hardware acceleration option in firefox.
If you disable this option almost everything works fine. Only if you change the timestamps then it can happen that the video still disappears for a second.

Should I add this information to the existing alert box?

**Comment by mzur** [comment]
Is there a Bugzilla issue about this that we can reference?

**Comment by lehecht** [comment]
I don't think so. On their official [support page](https://support.mozilla.org/de/kb/fehlerbehebung-bei-erweiterungen-themes-und-hardwarebeschleunigung#w_hardwarebeschleunigung-abschalten) they mention that the acceleration can cause problems and recommend to disable this option if it do so.

**Comment by lehecht** [comment]
Interestingly, there is no bug when using a machine with windows 10, firefox 124.0.1 and an AMD processor. So it is a platform dependent issue.

**Comment by mzur** [comment]
Ok thanks. Please leave this open and add any additional information you have (if any). I might get back to this because it annoys me :wink:
