### ISSUE TITLE
Regression with attach label interaction in video annotation tool

### ISSUE THREAD

**Issue by mzur** [biigle/core#641]
We had a bug report that can be reproduced as follows:

1. Create a label tree with at least two labels (or use an existing one)
2. Create a whole-frame video annotation
3. Split the annotation in the middle
4. Use the attach label interaction to add the second label to one of the parts of the annotation
5. Delete the first label from the part of the video annotation

Now an error "the server didn't respond" occurs. However, none of the requests fail and the label is correctly deleted. Find out why the error is displayed and fix it.

This seems to be a regression with a recent update because the error did not occur in a local branch of mine. In the most recent master branch it did occur. Maybe the commit introducing this error can be found with `git bisect`.

**Comment by lehecht** [comment]
> 5\. Delete the first label from the part of the video annotation

When I delete the first label, I only get the message "A label can only be deleted if it has no children and is not in use.". 
Or did you mean to delete the annotation of the first label?

**Comment by mzur** [comment]
I didn't mean to delete the label from the label tree. Instead, if you follow the instructions you should have one video annotation that has two labels attached to it. In 5. you should remove/detach the first label from this annotation.
