### ISSUE TITLE
Fix annotation tool image cache memory requirement

### ISSUE THREAD

**Issue by mzur** [biigle/core#653]
I just noticed that the cached images in the annotation tool can take up a huge amount of memory. I have a volume with high-resolution images (6720x4480) and 7 of these cached images require almost 1 GB of RAM. Currently, the cache is configured to retain up to [200 images](https://github.com/biigle/core/blob/8f9c0864c54bb7ee57d2a910f0ce7ba1bccafbe1/resources/assets/js/annotations/stores/images.vue#L15)! This crashed my machine when I viewed too many images.

I think the maximum cache size should equal the [cache size](https://github.com/biigle/core/blob/8f9c0864c54bb7ee57d2a910f0ce7ba1bccafbe1/resources/assets/js/annotations/annotatorContainer.vue#L67) configured in the annotation tool settings (maybe plus 1 or 2).

Also, we can explore if the memory requirement can be reduced in general. Each [cached image](https://github.com/biigle/core/blob/8f9c0864c54bb7ee57d2a910f0ce7ba1bccafbe1/resources/assets/js/annotations/stores/images.vue#L149-L152) has an `img` element (`source`) and a `canvas` element that contains the image again (possibly with applied color adjustment). There are several opportunities to reduce the memory requirements:

1. The `canvas` can be deleted if the image [has no CORS configured](https://github.com/biigle/core/blob/8f9c0864c54bb7ee57d2a910f0ce7ba1bccafbe1/resources/assets/js/annotations/stores/images.vue#L219). In this case the image is directly rendered from the `img`.

3. We don't really need one canvas for each image either. The canvas is used for color adjustment and to [fix the EXIF rotation](https://github.com/biigle/core/blob/8f9c0864c54bb7ee57d2a910f0ce7ba1bccafbe1/resources/assets/js/annotations/stores/images.vue#L63-L69). This can be probably done on the fly when an image should be rendered. Use a single canvas element, draw the new image, apply color adjustment and then pass it on to the OpenLayers map for drawing.

I think the multiple canvas elements with the uncompressed images are the main problem here.

**Comment by mzur** [comment]
@lehecht If this sounds interesting to you, feel free to assign yourself to the issue. It could get quite complicated, though. Otherwise I'll have a look when I find the time. I can imagine that this could be a big problem because high-resolution images are not that uncommon.

**Comment by dlangenk** [comment]
It might be a linux thing. I can easily cache 50 images (5.7x3.8k) with ~ 1GB of memory consumption in Firefox/Chrome (firefox needs a little more memory). How do you measure the memory consumption?

**Comment by mzur** [comment]
In `about:memory` in Firefox.
