### ISSUE TITLE
Small video loading spinner does not disappear

### ISSUE THREAD

**Issue by mzur** [biigle/core#695]
With the following actions, the small video loading spinner (on the top left of the video timeline) no longer disappears, even if nothing is loading:

1. Open a video in a volume with multiple videos
2. Click on a later time in the timeline to move the video forward, the small loading spinner will appear
3. Immediately click on the "next video" button
4. The big loading spinner (colorful steering wheel) will appear while the new video is loading
5. When the new video is loaded, the big loading spinner disappears but the small one won't disappear

While the (small) loading state is active, no clicks are allowed to jump the video time in the timeline, too.

To fix this, cancel the (small) loading action and state when the user changes to the next video.

**Comment by lehecht** [comment]
I struggle to recreate this bug.
Is the video already running before jumping to a later time stamp? 
The only thing that creates this bug for me, is if I hold the right arrow key for a couple of seconds. The next videos are displayed but the small grey spinner does not disappear any more. Do you think this behaviour has to do with this bug or is another one?

**Comment by mzur** [comment]
Your machine is probably faster than mine :smile: But what you describe sounds like what I see:

[Screencast from 15.12.2023 09:13:31.webm](https://github.com/biigle/core/assets/2457311/909e3332-4749-456d-8ccf-43d946ed0560)

Basically, the loading state for the lissle spinner has to be reset when a new video was loaded.
