### ISSUE TITLE
Sometimes the video position is not reset

### ISSUE THREAD

**Issue by mzur** [biigle/core#724]
Sometimes when I move the video position to a certain time and then switch to the next or previous video in the volume, the position is not reset to 0. Here is an example (wait for it):

[Screencast from 15.12.2023 10:43:38.webm](https://github.com/biigle/core/assets/2457311/542db8df-d81c-44e0-9f94-459759878fb9)

**Comment by lehecht** [comment]
Is there a reason why [this line](https://github.com/biigle/core/blob/997328ad3ee1da546c862f31efd13e69b6263149/resources/assets/js/videos/components/videoTimeline.vue#L230) is not used? If this is commented in, everything seems to work again.

**Comment by mzur** [comment]
No idea why this is there to be honest. I added it 5 years ago when I first implemented that component. I guess that I chose to use the `seeked` event instead. Maybe `timeupdate` already fires when the user clicks (i.e. `currentTime` is updated) whereas `seeked` only fires once the video actually loaded at that position.

Thinking about it, maybe using `timeupdate` *instead* of `seeked` may be a better UX because the user has instant feedback. There is still the loading state with the little spinner and the time indicator is gray until `seeked` is fired. What do you think?

**Comment by lehecht** [comment]
I agree that it would be better to use timeupdate only. It would also avoid redundant method calls when the video playback position is seeked.
