### ISSUE TITLE
Ignore zero-sized rectangles

### ISSUE THREAD

**Issue by mzur** [biigle/core#763]
We found out that some people are drawing lots of rectangles with zero size (i.e. all four points have the same coordinates. These rectangles should be ignored in the UI and not sent to the backend.

Also try to reproduce why this happens. Maybe people double-click when creating or finishing a rectangle? Then we should catch that, too.

**Comment by mzur** [comment]
This depends on how these zero-rectangles are created. If they are created involuntarily (e.g. a user draws a valid rectangle, then makes a double-click and thereby creates a second zero-rectangle) then I would say this should just be silently ignored. If zero-rectangles can only be created "intentionally" by clicking three times in a row on the same spot then maybe we should show a warning.

**Comment by neopaulit4n** [comment]
I am one of the users experiencing the zero-sized rectangles. I notice this happens whenever I start drawing a polygon using a straight horizontal line only. If I start drawing with a vertical or diagonal line, it never has this issue. However, starting to draw the polygon with a perfectly horizontal line then clicking the first time to set it causes the blue dashed drawing line to disappear every time. Nothing happens until you click again anywhere on the image (where you would normally want to draw the height of the polygon and complete the rectangle) and then an annotation appears in the annotations list, but the bounding box is invisible in the image itself.

**Comment by lehecht** [comment]
Unfortunately, I couldn't reproduce this bug. But with #769 everything seems to work. I can draw polygons like  @neopaulit4n described without any problems or weird behaviour.
