### ISSUE TITLE
Option to enable video audio

### ISSUE THREAD

**Issue by merlinbest5** [biigle/core#819]
Apologies if this has been discussed, but we would greatly benefit from having the audio playable in biigle videos. We often have scientists narrating various parts of the dive and the information can be very helpful for annotators (or at the very least entertaining).

**Comment by mzur** [comment]
Sounds like an easy thing to do. We could implement a switch in the annotation tool options to enable the audio.

**Comment by merlinbest5** [comment]
@mzur @dlangenk amazing! my team is really excited to have this function, many thanks for your efforts.
