### ISSUE TITLE
Image orientation is still incorrect in annotation tool

### ISSUE THREAD

**Issue by mzur** [biigle/core#833]
https://github.com/biigle/core/pull/809 attempted to fix the image auto-orientation. But we found an image that is still displayed incorrectly in Chrome (Firefox is correct): https://biigle.de/images/2240959/annotations

Previous discussion: https://github.com/biigle/magic-sam/issues/7#issuecomment-2116884024

**Comment by mzur** [comment]
@dlangenk It should be fixed now.

**Comment by dlangenk** [comment]
LGTM👍
