### ISSUE TITLE
A point or box to polygon conversion tool

### ISSUE THREAD

**Issue by dlangenk** [biigle/core#886]
With SAM we can convert points or boxes to polygons quite reliably, so we could make this available as a tool to convert (manual) annotations. We could either add the SAM based point, box -> polygon conversion tool to Maia or implement this as a separate tool, which reuses most of the MAIA UI for quality control. The python scripts are already there to perform the conversion.

**Comment by mzur** [comment]
Continued here: https://github.com/biigle/ptp/issues/1
