### ISSUE TITLE
Upload annotation to existing projects (metadata parsers)

### ISSUE THREAD

**Issue by dlangenk** [biigle/core#922]
Currently the metadata parsers like the ifdo parser can only be used to import annotations into a new volume. However, it would be great to import annotations to existing projects as well, especially in connection with a COCO parser to import e.g. machine learning annotations.

**Comment by mzur** [comment]
It should be possible to implement this rather easily with the existing code. When an import is initiated, a new PendingVolume is created from the existing Volume. The rest of the process can be the same.

**Comment by mzur** [comment]
@dlangenk This is now live on biigle.de. Feel free to give it a try.

**Comment by dlangenk** [comment]
I have already seen the "Closed as completed" mail and had a look in Biigle. I'll give it a try, but likely on Monday.
