### ISSUE TITLE
Bug - only appeared today - volume image overview only shows one row of thumbnails. 

### ISSUE THREAD

**Issue by TimWOceanSciences** [biigle/core#936]
Hello

Myself and another Biigle user have noticed that the volume overview image thumbnails are no longer organised in a grid but only about one row of thumbnails per page. See attached image. It was fine yesterday. 

Cheers

Tim 

![image](https://github.com/user-attachments/assets/626284f6-a5ed-4a23-a949-fdfbadedfd6b)

**Comment by mzur** [comment]
Thanks for the report! This will be fixed in a couple of minutes: https://github.com/biigle/core/pull/937

**Comment by TimWOceanSciences** [comment]
Cheers! Thanks for all the work, it’s a great platform.
