### ISSUE TITLE
Biigle Upload is pretty slow

### ISSUE THREAD

**Issue by dlangenk** [biigle/core#982]
The upload is especially slow in recent times (1.5h for roughly 200MB). Uploading to porta took about a minute for 1GB. Porta -> Biigle is also slow, so I don't think it is the connection speed.

**Comment by mzur** [comment]
Can you please monitor/test this over a couple of days? Maybe this was just a time when lots of users were uploading stuff.

**Comment by dlangenk** [comment]
This is already the second attempt. Storage Request 3881 was the first and 3941 the second with one week in between.

**Comment by dlangenk** [comment]
at least yesterday

**Comment by mzur** [comment]
The issue is caused by multiple small files that are uploaded sequentially. Parallel uploads will be implemented in https://github.com/biigle/user-storage/issues/3
