### ISSUE TITLE
Update volume creator during clone

### ISSUE THREAD

**Issue by mzur** [biigle/core#987]
When a volume is cloned, the creator is not updated. If the user who clones the volumes is a different user than the original creator, the `creator_id` should be updated to the user who cloned the volume.

**Comment by lehecht** [comment]
@mzur 
Has this bug any effect?

**Comment by mzur** [comment]
Yes, the `creator_id` ends up wrong :smile: For example, this makes the cloned volumes pop up as "recent activity" of the original creator instead of the user who actually cloned the volumes.
